# Generated by Django 6.0.4 on 2026-05-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Convidado/Família')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('declined', 'Não irá')], default='pending', max_length=20, verbose_name='Status da Confirmação')),
            ],
            options={
                'verbose_name': 'Convidado',
                'verbose_name_plural': 'Convidados',
            },
        ),
    ]
