# Generated by Django 6.0.4 on 2026-05-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Presente')),
                ('is_chosen', models.BooleanField(default=False, verbose_name='Já foi escolhido?')),
            ],
            options={
                'verbose_name': 'Presente',
                'verbose_name_plural': 'Lista de Presentes',
            },
        ),
    ]
